# Import GeoDjango models for spatial database fields
from django.contrib.gis.db import models


# Report model: Stores individual civic issue reports submitted by users
# Each report contains text information and a geographic point location
class Report(models.Model):
    # Title of the civic issue report (e.g., "Streetlight out")
    title = models.CharField(max_length=200)
    # Detailed description of the issue
    description = models.TextField()
    # Category classification (e.g., "Lighting", "Potholes", "Graffiti")
    category = models.CharField(max_length=100)
    # Geographic point location using WGS84 coordinate system (SRID 4326)
    # This allows spatial queries and distance calculations
    geom = models.PointField(srid=4326)
    # Timestamp automatically set when the report is created
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Database index on created_at for faster sorting by date
        indexes = [
            models.Index(fields=["created_at"], name="report_created_at_idx"),
        ]

    # String representation for admin interface and debugging
    def __str__(self):
        return f"{self.title} ({self.category})"


# Hotspot model: Stores detected clusters of reports as polygon areas
# Generated by DBSCAN clustering algorithm to identify problem areas
class Hotspot(models.Model):
    # Unique identifier for the cluster (assigned by DBSCAN algorithm)
    cluster_id = models.IntegerField()
    # Polygon geometry representing the boundary of the hotspot cluster
    # Uses WGS84 coordinate system (SRID 4326) for consistency with Report points
    geom = models.PolygonField(srid=4326)
    # Timestamp automatically set when the hotspot is created
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # Database indexes for faster queries by cluster_id and creation date
        indexes = [
            models.Index(fields=["cluster_id"], name="hotspot_cluster_idx"),
            models.Index(fields=["created_at"], name="hotspot_created_idx"),
        ]

    # String representation for admin interface and debugging
    def __str__(self):
        return f"Cluster {self.cluster_id}"
