# Import Django REST Framework router for automatic URL generation
from django.urls import path
from rest_framework.routers import DefaultRouter

from .views import HotspotViewSet, ReportViewSet, get_pois, login, logout, current_user, register

# Create a router instance to automatically generate URL patterns
router = DefaultRouter()
# Register ReportViewSet at /api/reports/ endpoint
# Provides: GET /api/reports/ (list), POST /api/reports/ (create)
#           GET /api/reports/{id}/ (detail), PUT/PATCH /api/reports/{id}/ (update)
#           DELETE /api/reports/{id}/ (delete)
router.register(r"reports", ReportViewSet, basename="report")
# Register HotspotViewSet at /api/hotspots/ endpoint
# Provides: GET /api/hotspots/ (list), GET /api/hotspots/{id}/ (detail)
# Note: Hotspots are read-only (auto-generated by clustering algorithm)
router.register(r"hotspots", HotspotViewSet, basename="hotspot")

# Export URL patterns generated by the router, plus custom POI endpoint
urlpatterns = router.urls + [
    # Authentication endpoints
    path("register/", register, name="register"),
    path("login/", login, name="login"),
    path("logout/", logout, name="logout"),
    path("current-user/", current_user, name="current-user"),
    # POI endpoint for Overpass API integration
    path("pois/", get_pois, name="pois"),
]


